name: Android Default Branch CI

on:
  push:
    branches:
      - shunf4_mod
      - master
      - 'fix/*'
      - 'feat/*'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-release
          path: ${{ steps.sign.outputs.signedReleaseFile }}
